name: Publish Website to CPanel

on:
  workflow_dispatch:
  
  repository_dispatch:
    type:
      - webhook
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-20.04

    steps:
      - name: 🚚 Get latest code
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache npm dependencies
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: 🔨 Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm install
          git reset --hard
      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
